folder_id = {}
folder_id.update({'Developer': '1amaMKP4nO-NcRoN37MZlSg_hgQrNnG03'})
folder_id.update({'Consultant': '1bpeYfZLZ4_fXfwJu9X1HCoSMObNCnGeI'})
folder_id.update({'Sales': '174NaRApV4HHNtQIZFu3Xf2ZErsXxp-yd'})
folder_id.update({'QA': '1awINuxw0PE92gQ6_9HDDRTPKBN9SKR0g'})
folder_id.update({'HR': '1PzEjSV6L1gxQl7GBtgNjLGuyYg7wvc9Q'})
folder_id.update({'Bussiness Developer Executive': '1kzH-kVTMTIta4phUeXCNaK2XCgjjWnoZ'})
folder_id.update({'UI Developer': '1ZR1q3i7AvXVKg-NAGmZae4L3hNswQkDe'})
folder_id.update({'Sales Executive': '1GruzNYSkeEq1pi-WjCIvUWURj4uRR_je'})
folder_id.update({'Web Developer': '1Ywg6oKDyY1AL0J1Q3pEgTdktZxKSUUBM'})
folder_id.update({'Content Writer': '1eLQXAqaTcCdToPb1OsRS5Kv7wOHoimKW'})
